# Generated by Django 3.1.8 on 2021-05-11 23:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20210510_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='weekday',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
