# Generated by Django 3.2.5 on 2021-07-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20210512_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='suspended',
            field=models.BooleanField(default=False),
        ),
    ]
